config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.6
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/im-dashboard:
      branch: devel
      repo: https://github.com/grycap/im-dashboard
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/im-dashboard git:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-teal-reindeer.sh
        container: qc.acc_tasty-russet-giraffe
  QC.Doc:
    repos:
      github.com/grycap/im-dashboard find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-purple-meerkat.sh
        container: qc.doc_jumpy-cream-spaniel
      github.com/grycap/im-dashboard git:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-purple-markhor.sh
        container: qc.doc_sunny-blue-iguana
      github.com/grycap/im-dashboard markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.silly-asparagus-warthog.sh
        container: qc.doc_hilly-indigo-peccary
  QC.Lic:
    repos:
      github.com/grycap/im-dashboard licensee:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-peach-ant.sh
        container: qc.lic_craggy-pink-wallaby
  QC.Met:
    repos:
      github.com/grycap/im-dashboard validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-azure-hound.sh
        container: qc.met_trippy-pear-tetra
  QC.Sec:
    repos:
      github.com/grycap/im-dashboard bandit:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-chestnut-iguana.sh
        container: qc.sec_flabby-apricot-quail
  QC.Sty:
    repos:
      github.com/grycap/im-dashboard flake8:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-cerise-quoll.sh
        container: qc.sty_flimsy-alizarin-dodo
      github.com/grycap/im-dashboard hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-gamboge-budgerigar.sh
        container: qc.sty_gummy-grey-lizard
      github.com/grycap/im-dashboard jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-ruby-slug.sh
        container: qc.sty_thirsty-cream-mongrel
      github.com/grycap/im-dashboard stylelint:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-smalt-millipede.sh
        container: qc.sty_bumpy-turquoise-warthog
  QC.Ver:
    repos:
      github.com/grycap/im-dashboard get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-emerald-tapir.sh
        container: qc.ver_homey-platinum-lynx
timeout: 1800
